; rg_arc_joypad - zlswap.ini
[rg_arc_joypad]
plugged = True
mouse = False
AnalogDeadzone = 0,0
AnalogPeak = 32768,32768
DPad R = 
DPad L = 
DPad D = 
DPad U = 
Start = button(9)
Z Trig = button(4)
B Button = button(2)
A Button = button(1)
C Button R = button(12)
C Button L = button(3)
C Button D = button(0)
C Button U = button(11)
R Trig = button(5)
L Trig = button(6)
Mempak switch = 
Rumblepak switch = 
# Analog axis configuration mappings
X Axis = button(15,16)
Y Axis = button(13,14)